### ISSUE TITLE
Update documentation based on re-write

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/specviz#466] opened 2018-10-23 14:59 UTC
The read-the-docs documentation needs to be updated based on the re-write.

**Comment by javerbukh** [comment] 2018-10-24 19:13
## Unit Conversion
Can convert the X or Y axis units into something different. Uses find_equivalent_units to populate potential X axis unit conversions and uses find_equivalent_units(equivalencies=u.spectral_density(spectral_units)) to populate potential Y axis unit conversions. Currently, the Y axis conversions do not work as intended, but they also are not buggy. This would be something that could be looked at by @nluetzge and @gderosa2004 once Unit Conversion functionality is merged. 
Example of what the code looks like:
```
import astropy.units as u
potential_X_axis_units = u.Unit(current_spectral_units).find_equivalent_units(equivalencies=u.spectral())
potential_Y_axis_units = u.Unit(current_spectral_units).find_equivalent_units(
                equivalencies=u.spectral_density(self.hub.data_item.spectral_axis))
```

Some example conversions:
X-axis: Angrstom to `['Meter', 'R_Jup', 'Joule', 'erg', 'Electronvolt', 'Hertz', 'Centimeter', 'Aa', 'Kayser', 'Curie', 'Becquerel', 'micron', 'Rydberg', 'Astronomical_Unit', 'R_Earth', 'Parsec', 'Lightyear', 'R_Sun', 'Angstrom', 'Custom']`
Y-axis: erg / (Angstrom cm2 s) to `['Meter', 'R_Jup', 'Centimeter', 'Aa', 'micron', 'Astronomical_Unit', 'R_Earth', 'Parsec', 'Lightyear', 'R_Sun', 'erg / (Angstrom cm2 s)', 'Custom']`

The Custom option is added by me and is handled in the code and the current unit is added to the list of conversions if it is not already in there.

**Comment by mfixstsci** [comment] 2018-10-24 21:02
# Layer Arithmetic

Currently the UI is ready to go and can perform calculations done on different components of spectrum1d objects if valid python is passed through the editor. Currently hooking the UI and backed to `specviz` via `workspace.py`. The calculated output still needs to be piped into a spectrum1d object that will stored in the data collection after the arithmetic is evaluated and there is still issue with injecting code that can be destructive via the equation editor `>>> os.remove(files)`.

**Comment by hcferguson** [comment] 2018-10-30 01:32
When the documents are updated the section called "Custom Loaders" should be preceded by a section called "Standard Loaders" or some such.

**Comment by eteq** [comment] 2018-11-02 17:18
With #512 now in, perhaps this should be closed in favor of fine-grained issues on particular topics? (with `documentation` label) @javerbukh and @mfixstsci should probably just put the content in this issue straight into the docs now via PRs?

**Comment by eteq** [comment] 2018-11-02 17:19
Although I just noticed RTD isn't building correctly so maybe closing should wait on the fixing of the RTD config.

**Comment by hcferguson** [comment] 2019-01-02 19:06
I think RTD finally worked, and agree that we can track further documentation updates in more fine-grained issues.

**Closed by hcferguson** 2019-01-02 19:06 UTC
Labels: documentation, priority-high, scope-5
