### ISSUE TITLE
Model problems

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#129] opened 2016-02-24 04:19 UTC
Encountering a few problems with models now:

- [ ] Initialization of the "mean" of the Gaussian doesn't look sensible in the case I'm trying. My ROI extends from 1-2 microns with a peak at about 1.7. The initial guess is 5.01.
- [x] If you change desktops on my Mac and then switch back (e.g. to type this issue), my selected parameter values vanish -- as if I hadn't selected the model at all.
- [x] When I create the layer, the color is so light sometimes (color selection seems random?) that I can't see the model.
- [x] When I tried to change the color of the model layer, it didn't change.

**Comment by ibusko** [comment] 2016-02-24 14:16
@hcferguson , what data are you using to initialize the Gaussian? I would like to try and reproduce the behavior you see.

**Comment by hcferguson** [comment] 2016-02-24 14:33
@ibusko I'm using example_spec_ascii.txt. It's attached on trello at https://trello.com/c/kXuhw1yl/46-test-data-location.

**Comment by ibusko** [comment] 2016-02-24 15:04
@hcferguson, I fixed the issue with the wrong initialization of Gaussian mean.

**Comment by ibusko** [comment] 2016-02-24 15:16
For item #2 above, I can reproduce the problem. Not only the parameters disappear, the entire model disappears. From that point on, the app will eventually crash in some funky state, depending on what sequence of UI actions you take.

I also noted that just minimizing the main app window, and then maximizing back, does not cause any problem.

Because the stack trace spewed out when the app breaks contained references to the initialization code, I repeated the experiment with the initialization code commented out. The issue still persists.

**Comment by nmearl** [comment] 2016-02-24 19:47
Updated some window behavior and the plot coloring based on your feedback. Please pull from master and check out the changes.

**Comment by ibusko** [comment] 2016-02-24 20:09
I just pushed a small fix in the fitting code that fixes the UI (and model layer) refresh when the fitted model has a single component. Also, the Dispatch.on_update_plot signal had to be renamed on_updated_plot. 

The problem now is that the parameter values properly refresh but the plot don't.

**Comment by nmearl** [comment] 2016-02-24 20:49
@ibusko checkout latest master.

**Comment by ibusko** [comment] 2016-02-24 21:30
It’s fixed now. Thanks!

**Comment by pllim** [comment] 2016-03-01 14:58
Closing. Feel free to reopen if needed.

**Closed by pllim** 2016-03-01 14:58 UTC
