### ISSUE TITLE
Dismiss removes all line list labels

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/specviz#397] opened 2018-04-20 16:01 UTC
It seems closing the dialog for the lists also removes the line labels from the plot, which is unexpected. It would be nice to keep the labels there and only remove them if the user presses the "Erase" button.

**Comment by ibusko** [comment] 2018-04-20 16:37
This is how the initial implementation used to behave. Closing the dialog for the lists was actually just a call to hide(). That preserved the labels on the plot. That led to a number of bugs though. Mostly caused by the state of objects not being clearly defined at certain points in the operation, especially when more than one spectrum is displayed, and each spectrum has it's own line lists dialog. Now that the thing is all in place and working, I bet it would be easier to solve the problem. Will work on that.

**Comment by ibusko** [comment] 2018-04-25 15:27
yes, the issue is solved with this commit. Should I generate a pull request?

**Comment by ibusko** [comment] 2018-04-25 15:32
I created a pull request that includes a fix for #310 as well (re-instate the black body model)

**Closed** 2018-04-25 17:24 UTC
Labels: enhancement

**Comment by nmearl** [comment] 2018-04-25 17:27
Thanks Ivo!
